import type { OrderSnapshot } from "./types";

const CATALOG: Record<string, OrderSnapshot> = {
  "1313972": {
    orderId: "1313972",
    user: "priya.m@gmail.com",
    charge: 3.2,
    link: "https://www.instagram.com/june_nwr1/",
    startCount: 410,
    current: 410,
    quantity: 1000,
    finalQuantity: 1410,
    service: "Instagram Followers [ High Quality ] [ Lifetime Refill Guarantee ] [ ULTRAFAST ]",
    orderStatus: "In progress",
    remains: 1000,
    createdAt: "2026-09-16 11:04:12",
    mode: "Auto",
  },
  "1315161": {
    orderId: "1315161",
    user: "dev.k@outlook.com",
    charge: 2.15,
    link: "https://www.instagram.com/reel/ABC123/",
    startCount: 88,
    current: 210,
    quantity: 500,
    finalQuantity: 588,
    service: "Instagram Likes [ Real ] [ Fast ]",
    orderStatus: "In progress",
    remains: 378,
    createdAt: "2026-09-17 18:22:01",
    mode: "Auto",
  },
  "1313494": {
    orderId: "1313494",
    user: "sana.t@gmail.com",
    charge: 6.4,
    link: "https://www.tiktok.com/@sana.clips",
    startCount: 1200,
    current: 1840,
    quantity: 2000,
    finalQuantity: 3200,
    service: "TikTok Followers [ HQ ]",
    orderStatus: "In progress",
    remains: 1360,
    createdAt: "2026-09-15 09:10:44",
    mode: "Auto",
  },
  "1313612": {
    orderId: "1313612",
    user: "omar.b@yahoo.com",
    charge: 1.8,
    link: "https://www.instagram.com/p/CzExample/",
    startCount: 42,
    current: 42,
    quantity: 200,
    finalQuantity: 242,
    service: "Instagram Likes [ Real ] [ Fast ]",
    orderStatus: "Pending",
    remains: 200,
    createdAt: "2026-09-17 21:02:33",
    mode: "Auto",
  },
  "1313984": {
    orderId: "1313984",
    user: "lee.park@gmail.com",
    charge: 8.9,
    link: "https://www.instagram.com/lee.park/",
    startCount: 2200,
    current: 2650,
    quantity: 1500,
    finalQuantity: 3700,
    service: "Instagram Followers [ High Quality ] [ Lifetime Refill Guarantee ] [ ULTRAFAST ]",
    orderStatus: "Partial",
    remains: 1050,
    createdAt: "2026-09-14 07:41:19",
    mode: "Auto",
  },
  "1308553": {
    orderId: "1308553",
    user: "rajanwarrior3@gmail.com",
    charge: 4.8048,
    link: "https://www.instagram.com/june_nwr1/",
    startCount: 822,
    current: 2222,
    quantity: 1400,
    finalQuantity: 2222,
    service: "Instagram Followers [ High Quality ] [ Lifetime Refill Guarantee ] [ ULTRAFAST ]",
    orderStatus: "Completed",
    remains: 0,
    createdAt: "2026-09-12 23:40:51",
    mode: "Auto",
  },
  "1314102": {
    orderId: "1314102",
    user: "nina.v@gmail.com",
    charge: 5.5,
    link: "https://www.youtube.com/watch?v=dQw",
    startCount: 340,
    current: 340,
    quantity: 1000,
    finalQuantity: 1340,
    service: "YouTube Views [ Retention ]",
    orderStatus: "Canceled",
    remains: 1000,
    createdAt: "2026-09-18 08:12:00",
    mode: "Manual",
  },
  "1314220": {
    orderId: "1314220",
    user: "kai.r@proton.me",
    charge: 4.1,
    link: "https://www.instagram.com/kai.reels/",
    startCount: 980,
    current: 1012,
    quantity: 800,
    finalQuantity: 1780,
    service: "Instagram Followers [ High Quality ] [ Lifetime Refill Guarantee ] [ ULTRAFAST ]",
    orderStatus: "In progress",
    remains: 768,
    createdAt: "2026-09-18 14:03:22",
    mode: "Auto",
  },
};

export function lookupOrder(orderId: string): OrderSnapshot {
  const id = orderId.trim();
  const known = CATALOG[id];
  if (known) return { ...known };

  const n = Number(id.replace(/\D/g, "").slice(-4) || "1200");
  return {
    orderId: id || "unknown",
    user: "unknown@customer.local",
    charge: Number(((n % 900) / 100 + 1.2).toFixed(2)),
    link: "https://www.instagram.com/example_profile/",
    startCount: n,
    current: n,
    quantity: 500,
    finalQuantity: n + 500,
    service: "Instagram Followers [ High Quality ] [ Lifetime Refill Guarantee ] [ ULTRAFAST ]",
    orderStatus: "In progress",
    remains: 500,
    createdAt: new Date().toISOString().slice(0, 19).replace("T", " "),
    mode: "Auto",
  };
}

export function isCatalogHit(orderId: string) {
  return Boolean(CATALOG[orderId.trim()]);
}
