/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminTeamRouteImport } from './routes/admin/team'
import { Route as ApiTestSmmqualityOrdersRouteImport } from './routes/api/test-smmquality-orders'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiSmmqualityOrderRouteImport } from './routes/api/smmquality/order'
import { Route as ApiSmmqualityServicesRouteImport } from './routes/api/smmquality/services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/admin/team',
  path: '/admin/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestSmmqualityOrdersRoute = ApiTestSmmqualityOrdersRouteImport.update({
  id: '/api/test-smmquality-orders',
  path: '/api/test-smmquality-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmmqualityOrderRoute = ApiSmmqualityOrderRouteImport.update({
  id: '/api/smmquality/order',
  path: '/api/smmquality/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmmqualityServicesRoute = ApiSmmqualityServicesRouteImport.update({
  id: '/api/smmquality/services',
  path: '/api/smmquality/services',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/team': typeof AdminTeamRoute
  '/api/test-smmquality-orders': typeof ApiTestSmmqualityOrdersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/smmquality/order': typeof ApiSmmqualityOrderRoute
  '/api/smmquality/services': typeof ApiSmmqualityServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/team': typeof AdminTeamRoute
  '/api/test-smmquality-orders': typeof ApiTestSmmqualityOrdersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/smmquality/order': typeof ApiSmmqualityOrderRoute
  '/api/smmquality/services': typeof ApiSmmqualityServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/team': typeof AdminTeamRoute
  '/api/test-smmquality-orders': typeof ApiTestSmmqualityOrdersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/smmquality/order': typeof ApiSmmqualityOrderRoute
  '/api/smmquality/services': typeof ApiSmmqualityServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/team'
    | '/api/test-smmquality-orders'
    | '/api/auth/$'
    | '/api/smmquality/order'
    | '/api/smmquality/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/team'
    | '/api/test-smmquality-orders'
    | '/api/auth/$'
    | '/api/smmquality/order'
    | '/api/smmquality/services'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/team'
    | '/api/test-smmquality-orders'
    | '/api/auth/$'
    | '/api/smmquality/order'
    | '/api/smmquality/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminTeamRoute: typeof AdminTeamRoute
  ApiTestSmmqualityOrdersRoute: typeof ApiTestSmmqualityOrdersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSmmqualityOrderRoute: typeof ApiSmmqualityOrderRoute
  ApiSmmqualityServicesRoute: typeof ApiSmmqualityServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/admin/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-smmquality-orders': {
      id: '/api/test-smmquality-orders'
      path: '/api/test-smmquality-orders'
      fullPath: '/api/test-smmquality-orders'
      preLoaderRoute: typeof ApiTestSmmqualityOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/smmquality/order': {
      id: '/api/smmquality/order'
      path: '/api/smmquality/order'
      fullPath: '/api/smmquality/order'
      preLoaderRoute: typeof ApiSmmqualityOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/smmquality/services': {
      id: '/api/smmquality/services'
      path: '/api/smmquality/services'
      fullPath: '/api/smmquality/services'
      preLoaderRoute: typeof ApiSmmqualityServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminTeamRoute: AdminTeamRoute,
  ApiTestSmmqualityOrdersRoute: ApiTestSmmqualityOrdersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSmmqualityOrderRoute: ApiSmmqualityOrderRoute,
  ApiSmmqualityServicesRoute: ApiSmmqualityServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
